### ISSUE TITLE
`np.int` was a deprecated alias for the builtin `int`.

### ISSUE THREAD

**Issue by fwarmuth** [mmatl/urdfpy#30]
Hey,
not working with recent NumPy versions >= 1.20!
```
from urdfpy import URDF
```
results in:
```
module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself.
Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision.
If you wish to review your current use, check the release note link for additional information.
```

Any plans on switching to builtin `int`?

regards

**Comment by thesofakillers** [comment]
+1

this is because [the networkx dependency is locked at 2.2](https://github.com/mmatl/urdfpy/blob/5466842899b33bd549e8f9e2a9a987bd5e37373b/setup.py#L8), which doesn't support numpy>1.20. 

Is there any reason to lock networkx at 2.2? This is causing issues in other repositories that depend on urdfpy.

see https://github.com/mmatl/urdfpy/issues/27

**Comment by deepansh96** [comment]
Facing the same issue. Any workaround?

**Comment by thesofakillers** [comment]
just use https://github.com/fishbotics/urchin instead of urdfpy, see #31
